version: '3.3'

services:
  psrdmaster:
    image: postgres:9.6
    command: >
      -c 'wal_level=hot_standby'
      -c 'wal_keep_segments=8'
      -c 'max_wal_senders=3'
      -c 'wal_keep_segments=8'
      -c 'hot_standby=on'
    ports:
      - 5432:5432
    volumes:
      - /tmp/psrdmaster:/var/lib/postgresql/data

  psrdstandby1:
    image: postgres:9.6 
    command: >
      -c 'wal_level=hot_standby'
      -c 'wal_keep_segments=8'
      -c 'max_wal_senders=3'
      -c 'wal_keep_segments=8'
      -c 'hot_standby=on'
    ports:
      - 5433:5432
    volumes:
      - /tmp/psrdstandby1:/var/lib/postgresql/data

#  pgsrstandby2:
#    image: postgres:9.6
#    ports:
#      - 5432:5434
#    volumes:
#      - /tmp/pgsrstandby2:/var/lib/postgresql/data
